# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'ios-challenge' do
    pod 'Alamofire', '~> 1.3'
    pod 'SwiftyJSON', '~> 2.2.1'
    pod 'Kingfisher', '~> 1.4'
    pod 'JTSImageViewController', '~> 1.4'
    pod 'RoundImageView', '~> 1.0.1'
    pod 'SwiftSpinner', '~> 0.7'
end

target 'ios-challengeTests' do

end

